<?php

namespace Tests\Feature\Hris;

use App\Models\CompanySetting;
use App\Models\Employee;
use App\Models\EmployeeAttendance;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AttendanceExportTest extends TestCase
{
    use RefreshDatabase;

    public function test_admin_can_export_attendance_as_pdf_with_kop(): void
    {
        $user = User::factory()->create([
            'email_verified_at' => now(),
        ]);

        CompanySetting::query()->create([
            'user_id' => $user->id,
            'name' => 'PT Sumber Makmur',
            'details' => 'Jl. Jenderal Sudirman No. 45, Jakarta Pusat',
            'location_address' => 'Gedung Wisma 46 Lt. 12',
        ]);

        $employee = Employee::factory()->create([
            'user_id' => $user->id,
            'first_name' => 'Aditya',
            'last_name' => 'Pratama',
            'timezone' => 'Asia/Jakarta',
        ]);

        EmployeeAttendance::factory()->create([
            'user_id' => $user->id,
            'employee_id' => $employee->id,
            'attendance_date' => today()->toDateString(),
            'status' => 'present',
            'timezone' => 'Asia/Jakarta',
            'check_in_at' => now()->setTime(8, 0),
            'check_out_at' => now()->setTime(17, 0),
            'check_in_photo_url' => 'https://example.com/checkin.jpg',
            'check_out_photo_url' => 'https://example.com/checkout.jpg',
            'face_similarity_score' => 0.9850,
        ]);

        $response = $this->actingAs($user)->get(route('hris.attendances.export', [
            'format' => 'pdf',
            'start_date' => today()->toDateString(),
            'end_date' => today()->toDateString(),
        ]));

        $response->assertOk();
        $this->assertEquals('application/pdf', $response->headers->get('content-type'));
        $contentDisposition = $response->headers->get('content-disposition') ?? '';
        $this->assertStringContainsString('.pdf', $contentDisposition);
    }

    public function test_attendance_export_xls_has_no_watermark_and_displays_wib(): void
    {
        $user = User::factory()->create([
            'email_verified_at' => now(),
        ]);

        CompanySetting::query()->create([
            'user_id' => $user->id,
            'name' => 'PT Sumber Makmur',
            'details' => 'Jakarta Pusat',
        ]);

        $employee = Employee::factory()->create([
            'user_id' => $user->id,
            'first_name' => 'Budi',
            'last_name' => 'Santoso',
            'timezone' => 'Asia/Jakarta',
        ]);

        EmployeeAttendance::factory()->create([
            'user_id' => $user->id,
            'employee_id' => $employee->id,
            'attendance_date' => today()->toDateString(),
            'status' => 'present',
            'timezone' => 'Asia/Jakarta',
            'check_in_at' => now()->setTime(8, 15),
            'check_out_at' => now()->setTime(17, 0),
        ]);

        $response = $this->actingAs($user)->get(route('hris.attendances.export', [
            'format' => 'xls',
            'start_date' => today()->toDateString(),
            'end_date' => today()->toDateString(),
        ]));

        $response->assertOk();
        $content = $response->streamedContent();

        // Must not contain watermark div
        $this->assertStringNotContainsString('class="watermark"', $content);
        $this->assertStringNotContainsString('watermark', $content);

        // Must contain "Generated by Humi" in footer only
        $this->assertStringContainsString('Generated by Humi', $content);

        // Timezone displayed as WIB instead of raw Asia/Jakarta
        $this->assertStringContainsString('Zona Waktu: WIB', $content);
        $this->assertStringContainsString('<td>WIB</td>', $content);
        $this->assertStringNotContainsString('Timezone: Asia/Jakarta', $content);
    }

    public function test_attendance_index_includes_photo_fields(): void
    {
        $this->withoutVite();

        $user = User::factory()->create([
            'email_verified_at' => now(),
        ]);

        $employee = Employee::factory()->create([
            'user_id' => $user->id,
            'first_name' => 'Citra',
            'last_name' => 'Lestari',
        ]);

        EmployeeAttendance::factory()->create([
            'user_id' => $user->id,
            'employee_id' => $employee->id,
            'attendance_date' => today()->toDateString(),
            'status' => 'present',
            'check_in_photo_url' => 'https://example.com/photos/in.jpg',
            'check_out_photo_url' => 'https://example.com/photos/out.jpg',
            'face_similarity_score' => 0.9520,
        ]);

        $response = $this->actingAs($user)->get(route('hris.attendances.index', [
            'date' => today()->toDateString(),
        ]));

        $response->assertOk();
        $response->assertInertia(fn ($page) => $page
            ->component('hris/attendances/index')
            ->has('attendances.data', 1)
            ->where('attendances.data.0.check_in_photo_url', 'https://example.com/photos/in.jpg')
            ->where('attendances.data.0.check_out_photo_url', 'https://example.com/photos/out.jpg')
            ->where('attendances.data.0.face_similarity_score', 0.952)
            ->where('attendances.data.0.has_photo', true)
        );
    }
}
