<?php

namespace Tests\Feature\Hris;

use App\Models\CompanySetting;
use App\Models\Employee;
use App\Models\EmployeeAttendance;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AttendanceExportTest extends TestCase
{
    use RefreshDatabase;

    public function test_attendance_export_includes_company_header_timestamp_and_humi_watermark(): void
    {
        $user = User::factory()->create([
            'email_verified_at' => now(),
        ]);

        CompanySetting::query()->updateOrCreate(
            ['user_id' => $user->id],
            [
                'name' => 'PT Test Company',
                'details' => "Jl. Merdeka No. 1\nMakassar",
            ],
        );

        $employee = Employee::factory()->create([
            'user_id' => $user->id,
            'employee_code' => 'EMP-001',
            'first_name' => 'Dio',
            'last_name' => 'Manuaba',
        ]);

        EmployeeAttendance::query()->create([
            'user_id' => $user->id,
            'employee_id' => $employee->id,
            'attendance_date' => '2026-05-21',
            'status' => 'present',
            'check_in_at' => '2026-05-21 08:00:00',
            'check_out_at' => '2026-05-21 17:00:00',
            'notes' => 'Tepat waktu',
        ]);

        $response = $this->actingAs($user)
            ->get(route('hris.attendances.export', ['date' => '2026-05-21']));

        $response->assertOk();
        $response->assertHeader('content-type', 'application/vnd.ms-excel; charset=UTF-8');

        $content = $response->streamedContent();

        $this->assertStringContainsString('PT Test Company', $content);
        $this->assertStringContainsString('Jl. Merdeka No. 1', $content);
        $this->assertStringContainsString('Laporan Kehadiran', $content);
        $this->assertStringContainsString('Generated at:', $content);
        $this->assertStringContainsString('Generated by Humi', $content);
        $this->assertStringContainsString('EMP-001', $content);
        $this->assertStringContainsString('Dio Manuaba', $content);
        $this->assertStringContainsString('08:00', $content);
        $this->assertStringContainsString('17:00', $content);
    }
}
