import { Check, ClipboardCheck, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { notifyPortal, requestApi, translatePortalError } from './lib';
import { PortalShell } from './shell';

type Item = { id: number; type: string; employee_label: string; stage: number; created_at: string | null };
const labels: Record<string, string> = { attendance: 'Absensi', leave: 'Cuti', overtime: 'Lembur', shift_change: 'Perubahan Jadwal' };

export default function PortalApprovalsPage({ pageTitle }: { pageTitle: string }) {
    const [items, setItems] = useState<Item[]>([]);
    const [processing, setProcessing] = useState<string | null>(null);
    const load = async () => { try { const response = await requestApi<{ items: Item[] }>('/portal/api/approvals'); setItems(response.data.items); } catch (error) { notifyPortal('error', error instanceof Error ? translatePortalError(error.message, 'Inbox approval tidak dapat dimuat.') : 'Inbox approval tidak dapat dimuat.'); } };
    useEffect(() => { void load(); }, []);
    const act = async (item: Item, action: 'approve' | 'reject') => { const key = `${item.type}-${item.id}`; const reason = action === 'reject' ? window.prompt('Alasan penolakan') : null; if (action === 'reject' && !reason) return; setProcessing(key); try { await requestApi(`/portal/api/approvals/${item.type}/${item.id}/${action}`, { method: 'POST', body: JSON.stringify(action === 'reject' ? { reason } : {}), headers: { 'Content-Type': 'application/json' } }); notifyPortal('success', action === 'approve' ? 'Approval berhasil diproses.' : 'Request ditolak.'); await load(); } catch (error) { notifyPortal('error', error instanceof Error ? translatePortalError(error.message, 'Approval gagal diproses.') : 'Approval gagal diproses.'); } finally { setProcessing(null); } };
    return <PortalShell title={pageTitle} eyebrow="Persetujuan" description="Proses pengajuan yang menunggu persetujuan Anda." active="approvals" links={{ attendance: '/portal/attendance', leaves: '/portal/leaves', overtimes: '/portal/overtimes', payroll: '/portal/payroll', activity: '/portal/activity', reprimands: '/portal/reprimands', approvals: '/portal/approvals' }}><section className="rounded-[16px] bg-white px-5 py-5 shadow-[0_16px_42px_rgba(15,23,42,0.07)]"><div className="flex items-center gap-3"><span className="portal-primary-soft inline-flex size-11 items-center justify-center rounded-lg"><ClipboardCheck className="portal-primary-text size-5" /></span><div><p className="text-xs tracking-[0.22em] text-slate-500 uppercase">Inbox approval</p><h2 className="mt-1 text-xl font-bold tracking-[-0.04em]">Menunggu persetujuan Anda</h2></div></div><div className="mt-5 space-y-3">{items.length ? items.map((item) => <article key={`${item.type}-${item.id}`} className="rounded-[12px] border border-stone-200/80 bg-stone-50 px-4 py-4"><p className="text-sm font-semibold">{labels[item.type]} · {item.employee_label}</p><p className="mt-1 text-sm text-slate-500">Tahap approval {item.stage} · Diajukan {item.created_at ?? '-'}</p><div className="mt-3 flex gap-2"><button disabled={processing === `${item.type}-${item.id}`} onClick={() => void act(item, 'approve')} className="inline-flex items-center gap-1 rounded-md bg-emerald-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50"><Check className="size-4" />Setujui</button><button disabled={processing === `${item.type}-${item.id}`} onClick={() => void act(item, 'reject')} className="inline-flex items-center gap-1 rounded-md bg-rose-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50"><X className="size-4" />Tolak</button></div></article>) : <p className="py-8 text-center text-sm text-slate-500">Tidak ada approval yang menunggu tindakan Anda.</p>}</div></section></PortalShell>;
}
